djangoOS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'', include('rango.urls', namespace='rango')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

rango/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rango import views

urlpatterns = patterns('',
    #url(r'^$', views.index, name='index'),
    #url(r'^about/$', views.about, name='about'),
    #url(r'^category/(?P<category_name_slug>\w+)$', views.category, name='category'),
    #url(r'^add_category/$', views.add_category, name='add_category'),
    #url(r'^category/(?P<category_name_slug>\w+)/add_page/$', views.add_page, name='add_page'),
    url(r'^$', views.index, name='home'),
    url(r'^add_cliente/$', views.add_cliente, name='add_cliente'), # NEW MAPPING!
    url(r'^abrir_os/$', views.add_servico, name='add_os'),
    url(r'^editar_servico/$', views.editar_servico, name='editar_servico'),
    url(r'^editar_servico/(?P<id>\d+)/$', views.editar_servico, name='editar_servico'),
    url(r'^historico/$', views.historico, name='historico'),
    url(r'^add_servico/busca_cliente/$', views.busca_cliente, name='search'),
    url(r'^add_cliente/busca_cliente/$', views.busca_cliente, name='search'),

)

rango/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Cliente(models.Model):
	primeiro_nome = models.CharField('primeiro nome', max_length=60)
	ultimo_nome = models.CharField('ultimo nome', max_length=60, blank=True, null=True)
	telefone = models.CharField('telefone', max_length=15, blank=True, null=True)
	email = models.EmailField('email', blank=True, null=True)
	def completa_nome(self):
		return self.primeiro_nome+" "+self.ultimo_nome
	def __str__(self):
		return self.nome_completo
	nome_completo = property(completa_nome)

	

class Oservico(models.Model):
	cliente = models.ForeignKey(Cliente)
	data_abertura = models.DateTimeField(default=timezone.now)
	equipamento = models.TextField(blank= True)
	defeito = models.TextField(blank= True)
	CHOICES = (('A', 'Aberta',), ('F', 'Fechada',), ('C', 'Cancelada', ))
	situacao = models.CharField(max_length=1, choices=CHOICES, default = 'A')
	solucao = models.TextField(blank= True)
	data_fechamento = models.DateTimeField(blank=True, null=True)  ## TODO ##


	class Meta:
		verbose_name='Ordem de Serviço'
		verbose_name_plural='Ordens de Serviço'

	def __str__(self):
		return str(self.pk)

	def abrir(self):
		self.save()

	#def get_absolute_url(self):
		#return reverse('rango:editar_historico', kwargs={'pk': self.pk})

rango/forms.py
from django import forms 
from django.forms import ModelForm
from rango.models import Cliente, Oservico
from django.utils import timezone
import datetime

#class ClienteForm(ModelForm):
	# class Meta:
	# 	model = Cliente
	# 	fields = ['primeiro_nome', 'ultimo_nome', 'telefone', 'email']

class ClienteForm(forms.ModelForm):
	primeiro_nome = forms.CharField(label='Primeiro Nome', max_length=60)
	ultimo_nome = forms.CharField(label='Ultimo nome', max_length=60)
	telefone = forms.CharField(label='telefone',max_length=15)
	email = forms.EmailField(label='e-mail')

	class Meta:
		model = Cliente
		fields = ['primeiro_nome', 'ultimo_nome', 'telefone', 'email']

#class ServicoForm(forms.Form):
#	busca = forms.CharField()

class ServicoForm(forms.ModelForm):
	data_abertura = forms.DateField(widget=forms.widgets.DateInput(format="%d/%m/%Y"))
	class Meta:
		model = Oservico
		fields = ['id','data_abertura', 'equipamento', 'defeito',]

class EditServicoForm(forms.ModelForm):
	def clean_ServicoForm(self):
		numero_os = self.cleaned_data['id']
		return numero_os
		
	class Meta:
		model = Oservico
		fields = ['id', 'cliente', 'situacao', 'solucao','data_fechamento' ]

def busca_usuarios():
	MY_CHOICES = (('1', 'Option 1'),('2', 'Option 2'),('3', 'Option 3'),)
	return MY_CHOICES

class MyForm(forms.Form):
	CLIENTE = forms.ChoiceField(choices=busca_usuarios())
	

rango/views.py
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from rango.forms import ClienteForm, ServicoForm, EditServicoForm
from rango.models import Oservico, Cliente
from django.core.context_processors import csrf

def index(request):
	args = {}
	args.update(csrf(request))
	args['clientes'] = Cliente.objects.all()
	return render(request, 'rango/index.html', args)

def add_cliente(request):
	#cliente = get_object_or_404(Cliente, )
	context = {}
	if request.method == 'POST':
		form = ClienteForm(request.POST)
		if form.is_valid():
			context['is_valid'] = True
			form.save()
			form = ClienteForm()
					
		else:
			print (form.errors)
	else:
		form = ClienteForm()
	context['form'] = form
	return render(request, 'rango/add_cliente.html', context)

# -- Tela de OS

def busca_cliente(request):
	if request.method == 'POST':
		search = request.POST['search_text']
	else:
		search = ' '
	clientes = Cliente.objects.filter(primeiro_nome__contains=search).exclude(primeiro_nome__contains=' ')
	return render_to_response('rango/ajax_search.html', {'clientes': clientes})	

def add_servico(request):
	#Oservico.objects.filter(cliente_id=id)
	context = {}
	if request.method == 'POST':
		form = ServicoForm(request.POST)
		if form.is_valid():
			context['is_valid'] = True
			form.save()
			form = ServicoForm()
		else:
			print (form.errors)
	else:
		form = ServicoForm()
	context['form'] = form
	return render(request, 'rango/add_os.html', context )

#Edit Form

def editar_servico(request, id):
	servico = get_object_or_404(Oservico, pk=id)
	form = EditServicoForm(request.POST or None, instance=servico)
	if form.is_valid():
		form.save()
		return redirect('rango:historico')			
	return render(request, 'rango/editar_servico.html', {'form': form} )

def historico(request):
	
	context = Oservico.objects.all()
	return render(request, 'rango/historico.html', {'context': context})

templates/rango/add_cliente.html
{% extends 'rango/base.html' %}
{% load bootstrap %}
    {% block content %}
<div class='col-sm-3' >
    <fieldset>
       
            <a class="btn btn-info" data-toggle="collapse" href="#adicionarcliente" aria-expanded="false" aria-controls="adicionarcliente">
                Adicionar Cliente
            </a>
                <div class="collapse" id="adicionarcliente">
                    <div class="well">
                         <form method="post" action="#cliente javascript:void(0)" >        
                            {% if is_valid %}
                            <div class="alert alert-success" role="alert"> <p> Cliente adicionado com sucesso. </p></div>
                            {% endif %}
                            {% csrf_token %}
                            <div >
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                                {% for field in form %}
                                    <div class='input-group input-group-lg'>  
                                    {{ field.label_tag }}
                                    <ul>{{ field }}
                                    {{ field.errors }}</ul>
                                    </div> 
                                {% endfor %}
            
                                <br />
                                <input class="btn btn-success" type="submit" name="submit" value="Gravar" />
                                <input class="btn btn-danger" type="submit" name="submit" value="Apagar" />
                            </div>
                            </form>
                    </div>
                </div>    
    </fieldset>
</div>
<div class='col-sm-9'>


    <form class="form-inline" method='POST' action="javascript:void(0)">
        <div class="form-group">
        <label for="tipo_busca">Buscar por:</label>
            {% csrf_token %}
            
            <select class="form-control" id='tipo_busca'>
                <option>Primeiro Nome</option>
                <option>Email</option>
                <option>Telefone</option>
                <option>Todos</option>
            </select>
            <input type='text' class='form-control' id='cliente_nome' name='cliente_nome' />
            <input class="btn btn-info" type="submit" id ='buscar_cliente' name="buscar_cliente" value="Procurar" />
        </div>
    </form>
    
    <div id='search-results'>

    </div>
     
</div>

   
    {% endblock %}

  

templates/rango/add_os.html
{% block content %}

Hello o/

{% endblock %}

templates/rango/add_servico.html
{% extends 'rango/base.html' %}
{% load bootstrap %}
    {% block content %}
    <fieldset>
    <form method="post" action="#cliente" >
        <h1>Add Serviço</h1>

        {% if is_valid %}
        <div class="alert alert-success" role="alert"> <p> Serviço adicionado com sucesso. </p></div>
        {% endif %}
            
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <div>
            
            <h3> Cliente </h3>
            {% csrf_token %}
            <input type='text' id='search' name='search' />
            <ul id='search-results' >
    
            </ul>
 
            {% for field in form %}
            
                <Ul>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
                </ul>
           
            {% endfor %}
            </div> 
            <br />
            <input class="btn btn-success" type="submit" name="submit" value="Gravar" />
            <input class="btn btn-danger" type="submit" name="submit" value="Apagar" />
        
        </div>
    </form>
    </fieldset>
   
   
    {% endblock %}

templates/rango/ajax_search.html
<br />
<table class="table table-bordered table-hover table-condensed ">
{% if clientes.count > 0 %}

<thead>
	<tr>
		<th data-field="id"><spam class= "glyphicon glyphicon-user"></spam> Cliente</th>
		<th data-field="telefone"><spam class= "glyphicon glyphicon-phone-alt"></spam> Telefone</th>
		<th data-field="opcao"><spam class="glyphicon glyphicon-cog"></spam> Opções</th>
	</tr>
</thead>
<tbody>
	{% for cliente in clientes %}
	<tr>
		<td>{{ cliente }}</td>
		<td>{{ cliente.telefone }}</td>

		<td>
			<button type="button" class="btn btn-default btn-sm" data-toggle='modal' data-target='#abreOsModal' aria-label="Left Align">
				Abrir OS
			</button>
		<!-- Abrir OS Modal -->
			<div class="modal fade" id="abreOsModal" tabindex="-1" role='dialog' aria-labelledby='abreOsModalLabel' aria-hidden='true'>
				<div class 'modal-dialog'>
					<div class='col-md-6 col-md-offset-3 modal-content '>
						<div class='modal-header'>
							<button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span>
							</button>
							<h4 class="modal-title" id="myModalLabel">Abertura de OS</h4>
						</div>
						<div class='modal-body'>
							Yololololo lorem lo
						</div>
						<div class='modal-footer'>
							<button type='button' class='btn btn-success'>Salvar</button>
                            <button type='button' class='btn btn-danger'>Cancelar</button>
						</div>
					</div>
				</div>
			</div>
		</td>
	</tr>
	{% endfor %}
   
</tbody>
</table>
	
{% endif %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Oservicos</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/logo-nav.css' %} " rel="stylesheet">

    <!-- Requisições Ajax -->
    <script src="http://code.jquery.com/jquery-2.0.0.js"></script>
   
    <script src="{% static 'js/ajax.js' %}"></script>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand " href="#">
                    <!--<img src="http://placehold.it/150x50&text=Logo" alt=""> -->
                  
                    
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav ">
                    <li>
                    	<a href="{% url 'rango:home' %}">Inicio </a>
                    </li>
                    <li>
                        <a href="{% url 'rango:historico' %}">Histórico</a>
                    </li>
                    <li>
                        <a href="{% url 'rango:add_cliente' %}">Clientes</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

		{% block content %}
		{% endblock %}
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src=" {% static 'js/jquery.js' %}"></script>


    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>



</body>

</html>

templates/rango/editar_servico.html
{% extends 'rango/base.html' %}
{% block content %}


<form method="POST">
    {% csrf_token %}
    {% if success %}
    <p>Os dados foram alterados com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div>
            {% if field == field.data_fechamento %}
                {{field | date:'d/m/Y' }}
            {% else %}
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            {% endif %}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Gravar</button>
            <button type="cancel" class="pure-button pure-button-secondary">Voltar</button>
        </div>
    </fieldset>
</form>
{% endblock %}

templates/rango/historico.html
{% extends 'rango/base.html' %}

{% block content %}


   

<table class="table table-bordered table-hover table-condensed ">
		


        <thead>
        	 <tr>

          		<th data-field="id">Numero OS</th>
           		<th data-field="data_abertura">Data Abertura</th>
           		<th data-field="nome">Nome Cliente</th>
                <th data-field="situacao">Situação</th>
                <th data-field="data_fechamento">Fechamento</th>

                <th data-field="opcao">Opções</th>

        	</tr>
    	</thead>
    	<tbody>

       
            {% for servico in context %}
    			<tr id="tr_id_1" class="tr-class-1">

    				<td>{{ servico.id }}</td>
    				<td>{{ servico.data_abertura | date:'d/m/Y' }}</td>
    				<td>{{ servico.cliente }}</td>
                    <td>{{ servico.situacao }}</td>
                    <td>{{ servico.data_fechamento | date:'d/m/Y' }}</td>                

                    <td>
                        <div class="btn-group" role="group" >
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="glyphicon glyphicon-wrench"></span></button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'rango:editar_servico' servico.id %}">Editar</a></li>
                            <li><a href="#">Concluir</span></a></li>
                        </ul>
                        </div>
                    </td>



    			</tr>
    		{% endfor %}
    	</tbody>
    </table>
    	

       <!-- {% for servico in context %}
        	<p>{{ servico.data_abertura }} - {{ servico.numero_os }} - {{ servico.cliente }} </p>
        {% endfor %} -->


{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}

{% block content %}



{% endblock %}

templates/rango/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>

    <body>
        <h1>Register with Rango</h1>
        <a href="/add_cliente/">Novo Cliente.</a><br />

    </body>
</html>